[nfs] 

51.144.155.49 ansible_ssh_user=Iyanu ansible_ssh_private_key_file=/home/Iyanu/.ssh/id_rsa 

[webservers]
23.101.77.106  ansible_ssh_user=Iyanu ansible_ssh_private_key_file=/home/Iyanu/.ssh/id_rsa


[all:vars] 
ansible_python_interpreter=/usr/bin/python3
