---
- name: update web, nfs and db servers
  hosts: webservers, nfs,
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
  - name: ensure wireshark is at the latest version
    yum:
      name: wireshark
      state: latest

- name: update LB server
  hosts: nfs
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
  - name: ensure wireshark is at the latest version
    apt:
      name: wireshark
      state: latest


- hosts: nfs, webservers
  tasks:
  - name: create directory
    file: 
       path: /home/Iyanu/Ansible
       state: directory

- hosts: all
  tasks:  
- name: Set Time Zone
  hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: Set timezone variables
      copy: content='America/Los_Angeles'
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - update timezone
  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata
